// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkiI0BH2sGDlFq346l-dfXoBXSd91BpU',
    appId: '1:998613954143:web:023d748c534ed71356b5ea',
    messagingSenderId: '998613954143',
    projectId: 'testapp-7c4e7',
    authDomain: 'testapp-7c4e7.firebaseapp.com',
    storageBucket: 'testapp-7c4e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GnTp94-UVJNhi0e7NAFO-m3kTD7LJqA',
    appId: '1:998613954143:android:92630583845e1cbf56b5ea',
    messagingSenderId: '998613954143',
    projectId: 'testapp-7c4e7',
    storageBucket: 'testapp-7c4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5OBDGGJ4I0zEUtznma3GQfMKrhv8An4',
    appId: '1:998613954143:ios:cc3238f4f1f7706056b5ea',
    messagingSenderId: '998613954143',
    projectId: 'testapp-7c4e7',
    storageBucket: 'testapp-7c4e7.appspot.com',
    iosBundleId: 'com.example.firebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB5OBDGGJ4I0zEUtznma3GQfMKrhv8An4',
    appId: '1:998613954143:ios:b5d8d6dc5e13dd2556b5ea',
    messagingSenderId: '998613954143',
    projectId: 'testapp-7c4e7',
    storageBucket: 'testapp-7c4e7.appspot.com',
    iosBundleId: 'com.example.firebaseBasics.RunnerTests',
  );
}
